basePath: /api
definitions:
  controllers.RefreshInput:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  models.UserLoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.UserRegisterDTO:
    properties:
      cpf:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - cpf
    - email
    - full_name
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: Sistema de Identidade Centralizado (SSO).
  title: Sentinel ID API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna Access Token e Refresh Token
      parameters:
      - description: Credenciais
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Realizar Login
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Revoga um Refresh Token específico
      parameters:
      - description: Token para revogar
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Gera um novo Access Token usando um Refresh Token válido
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Renovar Token (Refresh)
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Cria uma nova conta de usuário com senha criptografada
      parameters:
      - description: Dados de Cadastro
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registrar novo usuário
      tags:
      - Auth
  /users/revoke-all:
    post:
      description: Desconecta o usuário de TODOS os dispositivos
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Kill Switch (Revogar Tudo)
      tags:
      - Users
swagger: "2.0"
